#!/bin/sh
xsetroot -cursor_name left_ptr &
bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc monitor DVI-0 -d 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config focus_follows_pointer true

picom &
jgmenu --at-pointer &
xcape -e 'Super_L=Super_L|space' &
nitrogen --restore &
sxhkd -c ~/.config/bspwm/sxhkdrc &
polybar & 
dunst
